name: Deploy Oni

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@main
    with:
      applicationId: 5
      monitorIds: '5'
      environment: production
      deploymentName: oni
      imageName: oni